# this service is used to retrieve multiple settings
# list of settings requested if empty all settings will be returned
string[] requestednames
---
string[] names
string[] values
string[] descriptions
# is this setting used by a node during this session ?
bool[] inuse
